create table crm_sales_activities (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    subject varchar(255) not null,
    activity_type varchar(64) not null,
    activity_status varchar(64) not null,
    activity_result varchar(64),
    activity_time timestamp with time zone not null,
    next_follow_up_at timestamp with time zone,
    owner_department_id bigint not null references sys_departments(id),
    owner_user_id bigint not null references sys_users(id),
    communication_content text,
    customer_feedback text,
    conclusion text,
    next_plan text,
    risk_description text,
    include_in_weekly_progress boolean not null default true,
    weekly_period varchar(32),
    source_type varchar(64),
    source_ai_draft_id bigint,
    remark varchar(512),
    completed_at timestamp with time zone,
    completed_by bigint references sys_users(id),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_sales_activities_account
    on crm_sales_activities (account_id);

create index idx_crm_sales_activities_opportunity
    on crm_sales_activities (opportunity_id);

create index idx_crm_sales_activities_owner_time
    on crm_sales_activities (owner_user_id, activity_time);

create index idx_crm_sales_activities_status_time
    on crm_sales_activities (activity_status, activity_time);

create index idx_crm_sales_activities_next_follow
    on crm_sales_activities (next_follow_up_at);

create index idx_crm_sales_activities_weekly
    on crm_sales_activities (include_in_weekly_progress, activity_status);

create table crm_activity_contacts (
    activity_id bigint not null references crm_sales_activities(id),
    contact_id bigint not null references crm_contacts(id),
    created_at timestamp with time zone not null default current_timestamp,
    primary key (activity_id, contact_id)
);

create index idx_crm_activity_contacts_contact
    on crm_activity_contacts (contact_id);

create table crm_activity_participants (
    activity_id bigint not null references crm_sales_activities(id),
    user_id bigint not null references sys_users(id),
    participant_role varchar(64),
    created_at timestamp with time zone not null default current_timestamp,
    primary key (activity_id, user_id)
);

create index idx_crm_activity_participants_user
    on crm_activity_participants (user_id);

create table crm_activity_risk_types (
    activity_id bigint not null references crm_sales_activities(id),
    risk_type varchar(64) not null,
    created_at timestamp with time zone not null default current_timestamp,
    primary key (activity_id, risk_type)
);

create index idx_crm_activity_risk_types_type
    on crm_activity_risk_types (risk_type);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'activity.update', '编辑销售行动', 'operation', 'activity', 420
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'activity.update'
);
