create table crm_attachments (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    object_type varchar(64) not null,
    object_id bigint not null,
    file_name varchar(255) not null,
    file_url varchar(1024) not null,
    file_type varchar(64),
    file_size bigint,
    mime_type varchar(128),
    uploaded_by bigint references sys_users(id),
    uploaded_at timestamp with time zone not null default current_timestamp,
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_attachments_object
    on crm_attachments (object_type, object_id);

create index idx_crm_attachments_uploaded
    on crm_attachments (uploaded_by, uploaded_at);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'attachment.read', '查看附件', 'operation', 'attachment', 600
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'attachment.read'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'attachment.create', '新增附件', 'operation', 'attachment', 610
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'attachment.create'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'attachment.delete', '删除附件', 'operation', 'attachment', 620
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'attachment.delete'
);
