create table crm_reminders (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    object_type varchar(64) not null,
    object_id bigint not null,
    reminder_type varchar(64) not null,
    title varchar(255) not null,
    assignee_id bigint not null references sys_users(id),
    due_at timestamp with time zone not null,
    status varchar(32) not null default 'pending',
    completed_at timestamp with time zone,
    completed_by bigint references sys_users(id),
    cancelled_at timestamp with time zone,
    cancelled_by bigint references sys_users(id),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_reminders_assignee_due
    on crm_reminders (assignee_id, due_at);

create index idx_crm_reminders_status_due
    on crm_reminders (status, due_at);

create index idx_crm_reminders_object
    on crm_reminders (object_type, object_id);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'reminder.read', '查看提醒', 'operation', 'reminder', 700
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'reminder.read'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'reminder.update', '更新提醒', 'operation', 'reminder', 710
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'reminder.update'
);
