create table crm_solution_documents (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint not null references crm_opportunities(id),
    document_name varchar(255) not null,
    document_type varchar(64) not null,
    version_no varchar(64),
    status varchar(64) not null,
    owner_user_id bigint not null references sys_users(id),
    customer_requirement_summary text,
    technical_solution_summary text,
    stakeholder_strategy text,
    quotation_amount numeric(18, 2),
    cost_amount numeric(18, 2),
    estimated_gross_margin_rate numeric(8, 4),
    bid_self_check_result varchar(64),
    bid_risk_description text,
    submitted_to_customer_at timestamp with time zone,
    customer_feedback text,
    void_reason varchar(255),
    voided_at timestamp with time zone,
    voided_by bigint references sys_users(id),
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_solution_documents_account
    on crm_solution_documents (account_id);

create index idx_crm_solution_documents_opportunity
    on crm_solution_documents (opportunity_id);

create index idx_crm_solution_documents_status
    on crm_solution_documents (status);

create index idx_crm_solution_documents_owner
    on crm_solution_documents (owner_user_id);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'solution.read', '查看方案标书', 'operation', 'solution', 700
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'solution.read'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'solution.create', '新增方案标书', 'operation', 'solution', 710
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'solution.create'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'solution.update', '编辑方案标书', 'operation', 'solution', 720
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'solution.update'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'solution.void', '作废方案标书', 'operation', 'solution', 730
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'solution.void'
);
