create table crm_contracts (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    contract_name varchar(255) not null,
    contract_no varchar(128),
    contract_type varchar(64) not null,
    contract_status varchar(64) not null,
    contract_amount numeric(18, 2) not null,
    tax_rate numeric(8, 4),
    net_amount numeric(18, 2),
    our_signing_entity varchar(255),
    customer_signing_entity varchar(255),
    owner_user_id bigint not null references sys_users(id),
    business_owner_id bigint references sys_users(id),
    signed_at timestamp with time zone,
    effective_at timestamp with time zone,
    ended_at timestamp with time zone,
    payment_terms text,
    invoice_terms text,
    delivery_scope text,
    acceptance_criteria text,
    risk_level varchar(64),
    risk_description text,
    termination_reason varchar(512),
    terminated_at timestamp with time zone,
    terminated_by bigint references sys_users(id),
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_crm_contracts_no_active
    on crm_contracts (contract_no)
    ${activeRecordFilter};

create index idx_crm_contracts_account
    on crm_contracts (account_id);

create index idx_crm_contracts_opportunity
    on crm_contracts (opportunity_id);

create index idx_crm_contracts_status
    on crm_contracts (contract_status);

create index idx_crm_contracts_owner
    on crm_contracts (owner_user_id);

create table crm_contract_changes (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    contract_id bigint not null references crm_contracts(id),
    change_type varchar(64) not null,
    before_value text,
    after_value text,
    change_reason varchar(512) not null,
    changed_by bigint references sys_users(id),
    changed_at timestamp with time zone not null default current_timestamp
);

create index idx_crm_contract_changes_contract
    on crm_contract_changes (contract_id);

create table crm_contract_milestones (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    contract_id bigint not null references crm_contracts(id),
    milestone_name varchar(255) not null,
    milestone_type varchar(64) not null,
    planned_at timestamp with time zone,
    actual_at timestamp with time zone,
    status varchar(64) not null,
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_contract_milestones_contract
    on crm_contract_milestones (contract_id);

create index idx_crm_contract_milestones_status
    on crm_contract_milestones (status);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'contract.read', '查看合同', 'operation', 'contract', 800
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'contract.read'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'contract.create', '新增合同', 'operation', 'contract', 810
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'contract.create'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'contract.update', '编辑合同', 'operation', 'contract', 820
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'contract.update'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'contract.terminate', '终止合同', 'operation', 'contract', 830
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'contract.terminate'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'contract.milestone.manage', '管理合同节点', 'operation', 'contract', 840
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'contract.milestone.manage'
);
