create table crm_invoices (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    contract_id bigint not null references crm_contracts(id),
    plan_name varchar(255) not null,
    invoice_status varchar(64) not null,
    invoice_type varchar(64) not null,
    planned_invoice_date timestamp with time zone not null,
    planned_amount numeric(18, 2) not null,
    applied_amount numeric(18, 2),
    applied_at timestamp with time zone,
    applied_by bigint references sys_users(id),
    application_note varchar(512),
    invoice_code varchar(128),
    invoice_no varchar(128),
    invoice_date timestamp with time zone,
    tax_rate numeric(8, 4) not null,
    net_amount numeric(18, 2),
    tax_amount numeric(18, 2),
    actual_invoice_amount numeric(18, 2),
    signed_at timestamp with time zone,
    signed_by_name varchar(128),
    sign_note varchar(512),
    exception_type varchar(64),
    exception_reason varchar(512),
    exception_resolution varchar(512),
    void_reason varchar(512),
    voided_at timestamp with time zone,
    voided_by bigint references sys_users(id),
    owner_user_id bigint not null references sys_users(id),
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_invoices_account
    on crm_invoices (account_id);

create index idx_crm_invoices_opportunity
    on crm_invoices (opportunity_id);

create index idx_crm_invoices_contract
    on crm_invoices (contract_id);

create index idx_crm_invoices_status
    on crm_invoices (invoice_status);

create index idx_crm_invoices_owner
    on crm_invoices (owner_user_id);

create unique index uk_crm_invoices_no_active
    on crm_invoices (invoice_no)
    ${activeRecordFilter};

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.read', '查看开票', 'operation', 'invoice', 900
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.read'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.create', '新增开票计划', 'operation', 'invoice', 910
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.create'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.update', '编辑开票计划', 'operation', 'invoice', 920
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.update'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.apply', '提交开票申请', 'operation', 'invoice', 930
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.apply'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.issue', '登记发票', 'operation', 'invoice', 940
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.issue'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.sign', '确认发票签收', 'operation', 'invoice', 950
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.sign'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.exception', '登记开票异常', 'operation', 'invoice', 960
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.exception'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'invoice.void', '作废发票', 'operation', 'invoice', 970
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'invoice.void'
);
