create table crm_receivable_plans (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    contract_id bigint not null references crm_contracts(id),
    plan_name varchar(255) not null,
    plan_stage varchar(128),
    receivable_status varchar(64) not null,
    planned_receivable_date timestamp with time zone not null,
    planned_amount numeric(18, 2) not null,
    owner_user_id bigint not null references sys_users(id),
    payment_terms_snapshot varchar(512),
    overdue_reason varchar(128),
    termination_reason varchar(512),
    terminated_at timestamp with time zone,
    terminated_by bigint references sys_users(id),
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_crm_receivable_plans_account
    on crm_receivable_plans (account_id);

create index idx_crm_receivable_plans_opportunity
    on crm_receivable_plans (opportunity_id);

create index idx_crm_receivable_plans_contract
    on crm_receivable_plans (contract_id);

create index idx_crm_receivable_plans_status
    on crm_receivable_plans (receivable_status);

create index idx_crm_receivable_plans_owner
    on crm_receivable_plans (owner_user_id);

create index idx_crm_receivable_plans_date
    on crm_receivable_plans (planned_receivable_date);

create table crm_payments (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    contract_id bigint not null references crm_contracts(id),
    receivable_plan_id bigint references crm_receivable_plans(id),
    payment_name varchar(255) not null,
    payment_status varchar(64) not null,
    received_at timestamp with time zone not null,
    received_amount numeric(18, 2) not null,
    confirmed_amount numeric(18, 2) not null default 0,
    confirmed_at timestamp with time zone,
    confirmed_by bigint references sys_users(id),
    payment_method varchar(64) not null,
    payer_name varchar(255),
    receiving_account varchar(255),
    bank_flow_no varchar(128),
    reconciled_amount numeric(18, 2) not null default 0,
    exception_type varchar(64),
    exception_reason varchar(512),
    exception_resolution varchar(512),
    refund_reason varchar(512),
    refunded_at timestamp with time zone,
    refunded_by bigint references sys_users(id),
    owner_user_id bigint not null references sys_users(id),
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0,
    constraint chk_crm_payments_received_amount check (received_amount > 0),
    constraint chk_crm_payments_confirmed_amount check (confirmed_amount >= 0),
    constraint chk_crm_payments_reconciled_amount check (reconciled_amount >= 0),
    constraint chk_crm_payments_reconciled_lte_confirmed check (reconciled_amount <= confirmed_amount)
);

create index idx_crm_payments_account
    on crm_payments (account_id);

create index idx_crm_payments_opportunity
    on crm_payments (opportunity_id);

create index idx_crm_payments_contract
    on crm_payments (contract_id);

create index idx_crm_payments_plan
    on crm_payments (receivable_plan_id);

create index idx_crm_payments_status
    on crm_payments (payment_status);

create index idx_crm_payments_owner
    on crm_payments (owner_user_id);

create index idx_crm_payments_received_at
    on crm_payments (received_at);

create unique index uk_crm_payments_bank_flow_active
    on crm_payments (bank_flow_no)
    ${activeRecordFilter};

create table crm_receivable_follow_ups (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    contract_id bigint not null references crm_contracts(id),
    receivable_plan_id bigint not null references crm_receivable_plans(id),
    follow_up_at timestamp with time zone not null,
    follow_up_by bigint not null references sys_users(id),
    follow_up_content varchar(1024) not null,
    customer_feedback varchar(1024),
    next_action varchar(512),
    next_follow_up_at timestamp with time zone,
    remark varchar(512),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone
);

create index idx_crm_receivable_follow_ups_plan
    on crm_receivable_follow_ups (receivable_plan_id);

create index idx_crm_receivable_follow_ups_contract
    on crm_receivable_follow_ups (contract_id);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'receivable.read', '查看回款计划', 'operation', 'receivable', 1000
where not exists (select 1 from sys_permissions where permission_code = 'receivable.read');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'receivable.create', '新增回款计划', 'operation', 'receivable', 1010
where not exists (select 1 from sys_permissions where permission_code = 'receivable.create');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'receivable.update', '编辑回款计划', 'operation', 'receivable', 1020
where not exists (select 1 from sys_permissions where permission_code = 'receivable.update');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'receivable.terminate', '终止回款计划', 'operation', 'receivable', 1030
where not exists (select 1 from sys_permissions where permission_code = 'receivable.terminate');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'receivable.follow_up', '新增回款跟进', 'operation', 'receivable', 1040
where not exists (select 1 from sys_permissions where permission_code = 'receivable.follow_up');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'payment.read', '查看到账流水', 'operation', 'payment', 1050
where not exists (select 1 from sys_permissions where permission_code = 'payment.read');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'payment.create', '登记到账流水', 'operation', 'payment', 1060
where not exists (select 1 from sys_permissions where permission_code = 'payment.create');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'payment.update', '编辑到账流水', 'operation', 'payment', 1070
where not exists (select 1 from sys_permissions where permission_code = 'payment.update');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'payment.confirm', '确认到账', 'operation', 'payment', 1080
where not exists (select 1 from sys_permissions where permission_code = 'payment.confirm');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'payment.exception', '登记到账异常', 'operation', 'payment', 1090
where not exists (select 1 from sys_permissions where permission_code = 'payment.exception');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'payment.refund', '标记退款', 'operation', 'payment', 1100
where not exists (select 1 from sys_permissions where permission_code = 'payment.refund');
