alter table crm_invoices
    add column reconciled_amount numeric(18, 2) not null default 0;

alter table crm_invoices
    add constraint chk_crm_invoices_reconciled_amount
        check (reconciled_amount >= 0);

alter table crm_invoices
    add constraint chk_crm_invoices_reconciled_lte_actual
        check (actual_invoice_amount is null or reconciled_amount <= actual_invoice_amount);

create table crm_reconciliations (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_id bigint references crm_opportunities(id),
    contract_id bigint not null references crm_contracts(id),
    invoice_id bigint not null references crm_invoices(id),
    payment_id bigint not null references crm_payments(id),
    reconciliation_no varchar(128) not null,
    reconciliation_status varchar(64) not null,
    reconciled_amount numeric(18, 2) not null,
    reconciled_at timestamp with time zone not null,
    reconciled_by bigint not null references sys_users(id),
    reconcile_note varchar(512),
    void_reason varchar(512),
    voided_at timestamp with time zone,
    voided_by bigint references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0,
    constraint chk_crm_reconciliations_amount check (reconciled_amount > 0)
);

create unique index uk_crm_reconciliations_no_active
    on crm_reconciliations (reconciliation_no)
    ${activeRecordFilter};

create index idx_crm_reconciliations_account
    on crm_reconciliations (account_id);

create index idx_crm_reconciliations_opportunity
    on crm_reconciliations (opportunity_id);

create index idx_crm_reconciliations_contract
    on crm_reconciliations (contract_id);

create index idx_crm_reconciliations_invoice
    on crm_reconciliations (invoice_id);

create index idx_crm_reconciliations_payment
    on crm_reconciliations (payment_id);

create index idx_crm_reconciliations_status
    on crm_reconciliations (reconciliation_status);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'reconciliation.read', '查看核销', 'operation', 'reconciliation', 1110
where not exists (select 1 from sys_permissions where permission_code = 'reconciliation.read');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'reconciliation.create', '新增核销', 'operation', 'reconciliation', 1120
where not exists (select 1 from sys_permissions where permission_code = 'reconciliation.create');

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'reconciliation.void', '撤销核销', 'operation', 'reconciliation', 1130
where not exists (select 1 from sys_permissions where permission_code = 'reconciliation.void');
