create table sys_dict_types (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    dict_code varchar(64) not null,
    dict_name varchar(128) not null,
    description varchar(512),
    is_active boolean not null default true,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_sys_dict_types_code_active
    on sys_dict_types (tenant_id, dict_code)
    ${activeRecordFilter};

create table sys_dict_items (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    dict_type_id bigint not null references sys_dict_types(id),
    item_code varchar(64) not null,
    item_name varchar(128) not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_sys_dict_items_code_active
    on sys_dict_items (dict_type_id, item_code)
    ${activeRecordFilter};

create index idx_sys_dict_items_type_sort
    on sys_dict_items (dict_type_id, sort_order);

insert into sys_dict_types (dict_code, dict_name, description)
values
    ('account_type', '客户类型', 'CRM V1客户类型字典'),
    ('opportunity_stage', '商机阶段', 'CRM V1商机阶段字典'),
    ('activity_type', '行动类型', 'CRM V1销售行动类型字典');
