create table ai_input_records (
    id bigint generated by default as identity primary key,
    source_text text not null,
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp
);

create index idx_ai_input_records_created_by
    on ai_input_records (created_by, created_at);

create table ai_extraction_drafts (
    id bigint generated by default as identity primary key,
    input_record_id bigint not null references ai_input_records(id),
    draft_type varchar(64) not null,
    status varchar(64) not null,
    target_action varchar(64) not null,
    source_text text not null,
    payload_json text not null,
    missing_fields text,
    conflicts text,
    confidence_status varchar(64) not null,
    write_object_type varchar(64),
    write_object_id bigint,
    rejection_reason varchar(512),
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    confirmed_by bigint references sys_users(id),
    confirmed_at timestamp with time zone,
    rejected_by bigint references sys_users(id),
    rejected_at timestamp with time zone
);

create index idx_ai_extraction_drafts_owner_status
    on ai_extraction_drafts (created_by, status, created_at);

create index idx_ai_extraction_drafts_input
    on ai_extraction_drafts (input_record_id);

create table ai_write_logs (
    id bigint generated by default as identity primary key,
    draft_id bigint references ai_extraction_drafts(id),
    input_record_id bigint references ai_input_records(id),
    operation varchar(64) not null,
    object_type varchar(64),
    object_id bigint,
    status varchar(64) not null,
    error_message text,
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    trace_id varchar(128)
);

create index idx_ai_write_logs_draft
    on ai_write_logs (draft_id, created_at);

create index idx_ai_write_logs_actor
    on ai_write_logs (created_by, created_at);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'ai.draft.manage', '管理AI草稿', 'operation', 'ai', 1310
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'ai.draft.manage'
);
