create table ai_weekly_reports (
    id bigint generated by default as identity primary key,
    week_start_date date not null,
    week_end_date date not null,
    status varchar(64) not null,
    report_json text not null,
    source_activity_count integer not null default 0,
    write_activity_ids text,
    rejection_reason varchar(512),
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    confirmed_by bigint references sys_users(id),
    confirmed_at timestamp with time zone,
    rejected_by bigint references sys_users(id),
    rejected_at timestamp with time zone
);

create index idx_ai_weekly_reports_owner_status
    on ai_weekly_reports (created_by, status, created_at);

create index idx_ai_weekly_reports_period
    on ai_weekly_reports (created_by, week_start_date, week_end_date);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'ai.weekly.manage', '管理AI周报', 'operation', 'ai', 1320
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'ai.weekly.manage'
);
