create table sys_login_logs (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    user_id bigint,
    login_identifier varchar(255),
    event_type varchar(64) not null,
    success boolean not null,
    failure_reason varchar(512),
    ip_address varchar(64),
    user_agent varchar(512),
    trace_id varchar(128),
    occurred_at timestamp with time zone not null default current_timestamp
);

create index idx_sys_login_logs_user_time
    on sys_login_logs (user_id, occurred_at);

create index idx_sys_login_logs_identifier
    on sys_login_logs (login_identifier);

create index idx_sys_login_logs_event_type
    on sys_login_logs (event_type);

create table sys_audit_logs (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    actor_user_id bigint,
    module_code varchar(64) not null,
    action_code varchar(128) not null,
    object_type varchar(64),
    object_id bigint,
    before_data ${jsonDataType},
    after_data ${jsonDataType},
    result varchar(32) not null,
    failure_reason varchar(512),
    ip_address varchar(64),
    user_agent varchar(512),
    trace_id varchar(128),
    occurred_at timestamp with time zone not null default current_timestamp
);

create index idx_sys_audit_logs_actor_time
    on sys_audit_logs (actor_user_id, occurred_at);

create index idx_sys_audit_logs_object
    on sys_audit_logs (object_type, object_id);

create index idx_sys_audit_logs_module_time
    on sys_audit_logs (module_code, occurred_at);

create index idx_sys_audit_logs_action_code
    on sys_audit_logs (action_code);
