create table ai_visit_plans (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null references crm_opportunities(id),
    account_id bigint not null references crm_accounts(id),
    status varchar(64) not null,
    plan_json text not null,
    source_activity_count integer not null default 0,
    source_evidence_count integer not null default 0,
    write_activity_id bigint references crm_sales_activities(id),
    rejection_reason varchar(512),
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    confirmed_by bigint references sys_users(id),
    confirmed_at timestamp with time zone,
    rejected_by bigint references sys_users(id),
    rejected_at timestamp with time zone
);

create index idx_ai_visit_plans_owner_status
    on ai_visit_plans (created_by, status, created_at);

create index idx_ai_visit_plans_opportunity
    on ai_visit_plans (created_by, opportunity_id, created_at);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'ai.visit.plan', '生成AI拜访计划', 'operation', 'ai', 1340
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'ai.visit.plan'
);
