create table ai_communication_recommendations (
    id bigint generated by default as identity primary key,
    opportunity_id bigint not null references crm_opportunities(id),
    account_id bigint not null references crm_accounts(id),
    contact_id bigint not null references crm_contacts(id),
    status varchar(64) not null,
    recommendation_json text not null,
    source_activity_count integer not null default 0,
    source_evidence_count integer not null default 0,
    write_activity_id bigint references crm_sales_activities(id),
    rejection_reason varchar(512),
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    confirmed_by bigint references sys_users(id),
    confirmed_at timestamp with time zone,
    rejected_by bigint references sys_users(id),
    rejected_at timestamp with time zone
);

create index idx_ai_communication_recommendations_owner_status
    on ai_communication_recommendations (created_by, status, created_at);

create index idx_ai_communication_recommendations_opportunity
    on ai_communication_recommendations (created_by, opportunity_id, created_at);

create index idx_ai_communication_recommendations_contact
    on ai_communication_recommendations (created_by, contact_id, created_at);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'ai.communication.recommend', '生成AI沟通建议', 'operation', 'ai', 1350
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'ai.communication.recommend'
);
