create table sys_ai_model_configs (
    id bigint generated by default as identity primary key,
    provider varchar(64) not null,
    base_url varchar(512) not null,
    model_name varchar(128) not null,
    api_key_secret text not null,
    api_key_masked varchar(128) not null,
    enabled boolean not null default false,
    last_test_status varchar(64),
    last_test_message varchar(512),
    last_test_at timestamp with time zone,
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint references sys_users(id),
    updated_at timestamp with time zone
);

create index idx_sys_ai_model_configs_provider_enabled
    on sys_ai_model_configs (provider, enabled);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'system.ai-config.manage', '管理AI配置', 'operation', 'system', 1240
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'system.ai-config.manage'
);

insert into sys_role_permissions (role_id, permission_id)
select distinct rp.role_id, ai_config.id
from sys_role_permissions rp
join sys_permissions existing_permission on existing_permission.id = rp.permission_id
join sys_permissions ai_config on ai_config.permission_code = 'system.ai-config.manage'
where existing_permission.permission_code in ('system.role.manage', 'system.dict.manage')
  and not exists (
      select 1
      from sys_role_permissions existing_role_permission
      where existing_role_permission.role_id = rp.role_id
        and existing_role_permission.permission_id = ai_config.id
  );
