create table approval_templates (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    object_type varchar(64) not null,
    template_name varchar(255) not null,
    status varchar(32) not null default 'active',
    is_default boolean not null default false,
    created_by bigint not null references sys_users(id),
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint references sys_users(id),
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create index idx_approval_templates_object_status
    on approval_templates (tenant_id, object_type, status);

create index idx_approval_templates_default
    on approval_templates (tenant_id, object_type, is_default);

create table approval_template_nodes (
    id bigint generated by default as identity primary key,
    template_id bigint not null references approval_templates(id),
    step_order integer not null,
    node_name varchar(255) not null,
    approver_role_id bigint not null references sys_roles(id),
    status varchar(32) not null default 'active',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_approval_template_nodes_step unique (template_id, step_order)
);

create index idx_approval_template_nodes_role
    on approval_template_nodes (approver_role_id);

create table approval_instances (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    template_id bigint not null references approval_templates(id),
    object_type varchar(64) not null,
    object_id bigint not null,
    object_name varchar(255) not null,
    status varchar(32) not null default 'pending',
    current_step_order integer,
    submitted_by bigint not null references sys_users(id),
    submitted_at timestamp with time zone not null default current_timestamp,
    completed_at timestamp with time zone,
    result_comment text,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create index idx_approval_instances_object
    on approval_instances (tenant_id, object_type, object_id);

create index idx_approval_instances_status_step
    on approval_instances (tenant_id, status, current_step_order);

create index idx_approval_instances_template
    on approval_instances (template_id);

create index idx_approval_instances_submitter
    on approval_instances (submitted_by, submitted_at);

create table approval_instance_nodes (
    id bigint generated by default as identity primary key,
    instance_id bigint not null references approval_instances(id),
    step_order integer not null,
    node_name varchar(255) not null,
    approver_role_id bigint not null references sys_roles(id),
    status varchar(32) not null default 'pending',
    handled_by bigint references sys_users(id),
    handled_at timestamp with time zone,
    comment text,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_approval_instance_nodes_step unique (instance_id, step_order),
    constraint uk_approval_instance_nodes_instance_id unique (instance_id, id)
);

create index idx_approval_instance_nodes_role_status
    on approval_instance_nodes (approver_role_id, status);

create index idx_approval_instance_nodes_handler
    on approval_instance_nodes (handled_by, handled_at);

create table approval_actions (
    id bigint generated by default as identity primary key,
    instance_id bigint not null references approval_instances(id),
    node_id bigint,
    action varchar(32) not null,
    actor_user_id bigint not null references sys_users(id),
    comment text,
    action_at timestamp with time zone not null default current_timestamp,
    constraint fk_approval_actions_instance_node
        foreign key (instance_id, node_id)
        references approval_instance_nodes(instance_id, id)
);

create index idx_approval_actions_instance_time
    on approval_actions (instance_id, action_at);

create index idx_approval_actions_node
    on approval_actions (node_id);

create index idx_approval_actions_actor_time
    on approval_actions (actor_user_id, action_at);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'approval.read', '查看审批', 'operation', 'approval', 1300
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'approval.read'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'approval.submit', '提交审批', 'operation', 'approval', 1310
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'approval.submit'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'approval.approve', '处理审批', 'operation', 'approval', 1320
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'approval.approve'
);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'approval.config.manage', '管理审批配置', 'operation', 'approval', 1330
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'approval.config.manage'
);

insert into sys_role_permissions (role_id, permission_id)
select distinct rp.role_id, approval_permission.id
from sys_role_permissions rp
join sys_permissions existing_permission on existing_permission.id = rp.permission_id
join sys_permissions approval_permission on approval_permission.permission_code in (
    'approval.read', 'approval.submit', 'approval.approve', 'approval.config.manage'
)
where existing_permission.permission_code = 'system.role.manage'
  and not exists (
      select 1
      from sys_role_permissions existing_role_permission
      where existing_role_permission.role_id = rp.role_id
        and existing_role_permission.permission_id = approval_permission.id
  );
