create table sys_departments (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    parent_id bigint references sys_departments(id),
    code varchar(64) not null,
    name varchar(128) not null,
    region_code varchar(64),
    status varchar(32) not null default 'active',
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_sys_departments_code_active
    on sys_departments (tenant_id, code)
    ${activeRecordFilter};

create index idx_sys_departments_parent
    on sys_departments (parent_id);

create table sys_users (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    department_id bigint references sys_departments(id),
    name varchar(128) not null,
    mobile varchar(32),
    email varchar(255),
    role_code varchar(64),
    status varchar(32) not null default 'active',
    last_login_at timestamp with time zone,
    force_password_change boolean not null default false,
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_sys_users_mobile_active
    on sys_users (tenant_id, mobile)
    ${activeRecordFilter};

create unique index uk_sys_users_email_active
    on sys_users (tenant_id, email)
    ${activeRecordFilter};

create index idx_sys_users_department
    on sys_users (department_id);

create index idx_sys_users_status
    on sys_users (status);

create table sys_roles (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    code varchar(64) not null,
    name varchar(128) not null,
    description varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_sys_roles_code_active
    on sys_roles (tenant_id, code)
    ${activeRecordFilter};

create table sys_user_roles (
    user_id bigint not null references sys_users(id),
    role_id bigint not null references sys_roles(id),
    assigned_at timestamp with time zone not null default current_timestamp,
    primary key (user_id, role_id)
);

create index idx_sys_user_roles_role
    on sys_user_roles (role_id);

create table sys_login_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_users(id),
    login_type varchar(32) not null,
    login_identifier varchar(255) not null,
    is_primary boolean not null default false,
    status varchar(32) not null default 'active',
    failed_login_count integer not null default 0,
    last_failed_login_at timestamp with time zone,
    locked_until timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create unique index uk_sys_login_accounts_identifier
    on sys_login_accounts (login_type, login_identifier);

create index idx_sys_login_accounts_user
    on sys_login_accounts (user_id);

create index idx_sys_login_accounts_status
    on sys_login_accounts (status);

create table sys_user_credentials (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_users(id),
    credential_type varchar(32) not null,
    password_hash varchar(255) not null,
    password_algo varchar(64) not null,
    password_updated_at timestamp with time zone not null default current_timestamp,
    password_expires_at timestamp with time zone,
    status varchar(32) not null default 'active',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create unique index uk_sys_user_credentials_type
    on sys_user_credentials (user_id, credential_type);

create table sys_permissions (
    id bigint generated by default as identity primary key,
    parent_id bigint references sys_permissions(id),
    permission_code varchar(128) not null,
    permission_name varchar(128) not null,
    permission_type varchar(32) not null,
    module_code varchar(64) not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create unique index uk_sys_permissions_code
    on sys_permissions (permission_code);

create index idx_sys_permissions_module
    on sys_permissions (module_code);

create index idx_sys_permissions_parent
    on sys_permissions (parent_id);

create table sys_role_permissions (
    role_id bigint not null references sys_roles(id),
    permission_id bigint not null references sys_permissions(id),
    granted_at timestamp with time zone not null default current_timestamp,
    primary key (role_id, permission_id)
);

create index idx_sys_role_permissions_permission
    on sys_role_permissions (permission_id);

create table sys_data_scopes (
    id bigint generated by default as identity primary key,
    scope_code varchar(64) not null,
    scope_name varchar(128) not null,
    description varchar(512)
);

create unique index uk_sys_data_scopes_code
    on sys_data_scopes (scope_code);

create table sys_role_data_scopes (
    role_id bigint not null references sys_roles(id),
    module_code varchar(64) not null,
    data_scope_id bigint not null references sys_data_scopes(id),
    primary key (role_id, module_code, data_scope_id)
);

create index idx_sys_role_data_scopes_module
    on sys_role_data_scopes (module_code);

create index idx_sys_role_data_scopes_scope
    on sys_role_data_scopes (data_scope_id);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
values
    ('system.user.manage', '管理用户', 'operation', 'system', 10),
    ('system.role.manage', '管理角色权限', 'operation', 'system', 20),
    ('system.dict.manage', '管理字典', 'operation', 'system', 30),
    ('system.audit.read', '查看审计日志', 'operation', 'system', 40),
    ('account.read', '查看客户', 'operation', 'account', 100),
    ('account.create', '新建客户', 'operation', 'account', 110),
    ('account.update', '编辑客户', 'operation', 'account', 120),
    ('contact.read', '查看联系人', 'operation', 'contact', 200),
    ('contact.create', '新建联系人', 'operation', 'contact', 210),
    ('opportunity.read', '查看商机', 'operation', 'opportunity', 300),
    ('opportunity.create', '新建商机', 'operation', 'opportunity', 310),
    ('opportunity.update', '编辑商机', 'operation', 'opportunity', 320),
    ('activity.read', '查看销售行动', 'operation', 'activity', 400),
    ('activity.create', '新建销售行动', 'operation', 'activity', 410),
    ('weekly_progress.read', '查看周进展', 'operation', 'weekly_progress', 500);

insert into sys_data_scopes (scope_code, scope_name, description)
values
    ('own', '本人数据', '仅本人负责的数据'),
    ('department', '本部门数据', '本人所在部门数据'),
    ('department_tree', '本部门及下级数据', '本人所在部门及下级组织数据'),
    ('collaborated', '协同数据', '本人参与协同的数据'),
    ('global', '全部数据', '全局数据范围');
