create table sys_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_users(id),
    login_account_id bigint references sys_login_accounts(id),
    session_token_hash varchar(128) not null,
    ip_address varchar(64),
    user_agent varchar(512),
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp
);

create unique index uk_sys_sessions_token_hash
    on sys_sessions (session_token_hash);

create index idx_sys_sessions_user
    on sys_sessions (user_id);

create index idx_sys_sessions_expires
    on sys_sessions (expires_at);

create index idx_sys_sessions_revoked
    on sys_sessions (revoked_at);
