create table crm_accounts (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    parent_id bigint references crm_accounts(id),
    account_name varchar(255) not null,
    account_short_name varchar(128),
    account_type varchar(64) not null,
    account_level varchar(32),
    account_status varchar(32) not null,
    account_source varchar(64),
    industry varchar(128),
    region_province varchar(64),
    region_city varchar(64),
    address varchar(255),
    relationship_status varchar(64),
    owner_department_id bigint not null references sys_departments(id),
    owner_user_id bigint not null references sys_users(id),
    background text,
    key_needs text,
    last_activity_at timestamp with time zone,
    last_activity_summary varchar(512),
    next_follow_up_at timestamp with time zone,
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_crm_accounts_name_active
    on crm_accounts (tenant_id, account_name)
    ${activeRecordFilter};

create index idx_crm_accounts_owner_user
    on crm_accounts (owner_user_id);

create index idx_crm_accounts_owner_department
    on crm_accounts (owner_department_id);

create index idx_crm_accounts_parent
    on crm_accounts (parent_id);

create index idx_crm_accounts_level_status
    on crm_accounts (account_level, account_status);

create index idx_crm_accounts_region
    on crm_accounts (industry, region_province, region_city);

create index idx_crm_accounts_last_activity
    on crm_accounts (last_activity_at);

create table crm_account_collaborators (
    account_id bigint not null references crm_accounts(id),
    user_id bigint not null references sys_users(id),
    collaborator_role varchar(64),
    created_at timestamp with time zone not null default current_timestamp,
    primary key (account_id, user_id)
);

create index idx_crm_account_collaborators_user
    on crm_account_collaborators (user_id);

create index idx_crm_account_collaborators_role
    on crm_account_collaborators (collaborator_role);
