create table crm_contacts (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    name varchar(128) not null,
    department varchar(128),
    title varchar(128),
    mobile varchar(64),
    mobile_normalized varchar(64),
    email varchar(128),
    wechat varchar(128),
    contact_type varchar(64),
    decision_influence varchar(64),
    attitude varchar(64),
    relationship_heat varchar(64),
    importance_level varchar(64),
    birthday date,
    anniversary date,
    last_communication_at timestamp with time zone,
    last_communication_summary varchar(512),
    next_action varchar(512),
    owner_department_id bigint not null references sys_departments(id),
    owner_user_id bigint not null references sys_users(id),
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_crm_contacts_mobile_active
    on crm_contacts (tenant_id, account_id, name, mobile_normalized)
    ${activeRecordFilter};

create index idx_crm_contacts_account
    on crm_contacts (account_id);

create index idx_crm_contacts_owner_user
    on crm_contacts (owner_user_id);

create index idx_crm_contacts_owner_department
    on crm_contacts (owner_department_id);

create index idx_crm_contacts_type
    on crm_contacts (contact_type);

create index idx_crm_contacts_attitude
    on crm_contacts (attitude);

create index idx_crm_contacts_relationship_heat
    on crm_contacts (relationship_heat);

create index idx_crm_contacts_last_communication
    on crm_contacts (last_communication_at);

create table crm_contact_project_roles (
    contact_id bigint not null references crm_contacts(id),
    role_code varchar(64) not null,
    created_at timestamp with time zone not null default current_timestamp,
    primary key (contact_id, role_code)
);

create index idx_crm_contact_project_roles_role
    on crm_contact_project_roles (role_code);

insert into sys_permissions (permission_code, permission_name, permission_type, module_code, sort_order)
select 'contact.update', '编辑联系人', 'operation', 'contact', 220
where not exists (
    select 1
    from sys_permissions
    where permission_code = 'contact.update'
);
