create table crm_opportunities (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null default 1,
    account_id bigint not null references crm_accounts(id),
    opportunity_name varchar(255) not null,
    stage varchar(64) not null,
    status varchar(64) not null,
    level varchar(32),
    source varchar(64),
    potential_point text,
    opportunity_analysis text,
    project_requirement text,
    estimated_budget_amount numeric(18, 2),
    estimated_contract_amount numeric(18, 2),
    estimated_gross_margin_rate numeric(8, 4),
    expected_close_date date,
    project_cycle varchar(255),
    procurement_process text,
    funding_source varchar(128),
    owner_department_id bigint not null references sys_departments(id),
    owner_user_id bigint not null references sys_users(id),
    technical_solution_status varchar(64),
    stakeholder_plan_status varchar(64),
    quotation_status varchar(64),
    bid_self_check_status varchar(64),
    current_progress text,
    next_plan text,
    risk_status varchar(32),
    risk_description text,
    win_rate numeric(8, 4),
    last_activity_at timestamp with time zone,
    last_activity_summary varchar(512),
    close_type varchar(64),
    close_reason varchar(128),
    close_description text,
    closed_at timestamp with time zone,
    closed_by bigint references sys_users(id),
    can_reopen boolean not null default false,
    remark varchar(512),
    created_by bigint,
    created_at timestamp with time zone not null default current_timestamp,
    updated_by bigint,
    updated_at timestamp with time zone not null default current_timestamp,
    deleted_at timestamp with time zone,
    version integer not null default 0
);

create unique index uk_crm_opportunities_name_active
    on crm_opportunities (tenant_id, account_id, opportunity_name)
    ${activeRecordFilter};

create index idx_crm_opportunities_account
    on crm_opportunities (account_id);

create index idx_crm_opportunities_owner_user
    on crm_opportunities (owner_user_id);

create index idx_crm_opportunities_owner_department
    on crm_opportunities (owner_department_id);

create index idx_crm_opportunities_stage_status
    on crm_opportunities (stage, status);

create index idx_crm_opportunities_expected_close
    on crm_opportunities (expected_close_date);

create index idx_crm_opportunities_risk
    on crm_opportunities (risk_status);

create index idx_crm_opportunities_last_activity
    on crm_opportunities (last_activity_at);

create table crm_opportunity_collaborators (
    opportunity_id bigint not null references crm_opportunities(id),
    user_id bigint not null references sys_users(id),
    collaborator_role varchar(64),
    created_at timestamp with time zone not null default current_timestamp,
    primary key (opportunity_id, user_id)
);

create index idx_crm_opportunity_collaborators_user
    on crm_opportunity_collaborators (user_id);

create index idx_crm_opportunity_collaborators_role
    on crm_opportunity_collaborators (collaborator_role);

create table crm_opportunity_contacts (
    opportunity_id bigint not null references crm_opportunities(id),
    contact_id bigint not null references crm_contacts(id),
    role_in_opportunity varchar(64),
    is_key_person boolean not null default false,
    created_at timestamp with time zone not null default current_timestamp,
    primary key (opportunity_id, contact_id)
);

create index idx_crm_opportunity_contacts_contact
    on crm_opportunity_contacts (contact_id);

create index idx_crm_opportunity_contacts_role
    on crm_opportunity_contacts (role_in_opportunity);

create index idx_crm_opportunity_contacts_key_person
    on crm_opportunity_contacts (is_key_person);
