spring:
  application:
    name: crm-ai-backend
  datasource:
    url: ${CRM_DB_URL}
    username: ${CRM_DB_USERNAME}
    password: ${CRM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      activeRecordFilter: where deleted_at is null

server:
  port: 8080
